package com.example.mycarstore.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "splashscreen"
const val AUDIQ7_URL = "audiq7"
const val HARRIER1_URL = "harrier1"
const val HARRIER2_URL = "harrier2"
const val COROLLA1_URL = "corolla1"
const val CRV_URL = "crv"
const val CX3_URL = "cx3"
const val CX5_URL = "cx5"
const val VOGUE_URL = "vogue"
const val CROWN_URL = "crown"
const val EVOQUE_URL = "evoque"
const val VITZ_URL = "vitz"
const val SELL_URL = "sell"
